# Generated by Django 4.2.20 on 2025-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
