# Generated by Django 5.2 on 2025-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_show_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='available_seats',
        ),
        migrations.AlterField(
            model_name='show',
            name='total_seats',
            field=models.PositiveIntegerField(),
        ),
    ]
