# Generated by Django 5.2 on 2025-04-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_remove_show_available_seats_alter_show_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='show',
            name='total_seats',
            field=models.IntegerField(),
        ),
    ]
